# This file was generated by GoReleaser. DO NOT EDIT.
cask "wx" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2819f28485db0c42467e662cab937222f02b5319ec3556eafb71023cd08351a2"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8a50646df8f8ce702bd57828b5738ec94a8c643a11b3e111031b4609cdd0e550"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b06bbdc2ee0b21aaae3e030af741723dec8c1922985baef17dc427d6a99f72c"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bb6d12a20b73d59cbdd173579ddcc77721d680afd206e185c7421450a86b654f"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Linux_arm64.tar.gz"
    end
  end

  name "wx"
  desc "Native command-line interface for wxrks APIs."
  homepage "https://github.com/wxrks-hq/wx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wx"

  # No zap stanza required

end
