# This file was generated by GoReleaser. DO NOT EDIT.
cask "wx" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "60d70f2874026296ae976e5accf80047e67226e935a319d7462a851a0a0a6f87"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d900dcedbec53fe78a6d6794954ba565fc47265c4b9606d4e7c1670847d6c98f"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e4e7380f22b62c2a12906b58fbdd4e8dd85cf29267bd74632fcac1afed675b9"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f04b0e9fbd98b6da6233ab12dc7e83275b0f4d796fc5d11576cc7a8d512256c6"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Linux_arm64.tar.gz"
    end
  end

  name "wx"
  desc "Native command-line interface for wxrks APIs."
  homepage "https://github.com/wxrks-hq/wx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wx"

  # No zap stanza required

end
