# This file was generated by GoReleaser. DO NOT EDIT.
cask "wx" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "12f168f479329f4e6c930b44bdaa19fb2a0fed0c0e9ba9e0595dd01df9220837"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f02a5528aadcb7c4875703908f0881be2e77218e4d3ee6dc6c23c35e7e21d992"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66c39caca3e0b427e99ba55ca9121b1f1b6fede2ecb85b784e94dfc36e66ebb0"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "04a2b13e5e33aa401b5a024e3410a9c81d4cfb46e9e08f612f8bd4e5ae350b9e"
      url "https://github.com/wxrks-hq/wx/releases/download/v#{version}/wx_Linux_arm64.tar.gz"
    end
  end

  name "wx"
  desc "Native command-line interface for wxrks APIs."
  homepage "https://github.com/wxrks-hq/wx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wx"

  # No zap stanza required

end
